esphome:
  name: garage-gate
  platform: ESP8266
  board: nodemcuv2

# WiFi configuration - use secrets for credentials
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "Garage Gate Fallback"
    password: !secret fallback_password

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

# Enable Over-The-Air updates
ota:
  - platform: esphome
    password: !secret ota_password

# Web server for standalone access (optional)
web_server:
  port: 80

# Status LED (optional - uses built-in LED on NodeMCU)
# GPIO2 (D4) is the built-in LED on NodeMCU boards
status_led:
  pin:
    number: GPIO2
    inverted: true

# Binary sensor for the contactron (gate position sensor)
# Assumes contactron is connected to GPIO14 (D5 on NodeMCU)
# When gate is closed, contactron is closed (LOW), when open it's open (HIGH)
binary_sensor:
  - platform: gpio
    id: gate_contactron
    name: "Garage Gate Position Sensor"
    pin:
      number: GPIO14  # D5
      mode:
        input: true
        pullup: true
      inverted: true
    device_class: garage_door
    filters:
      - delayed_on: 100ms
      - delayed_off: 100ms
    on_press:
      then:
        - logger.log: "Gate is CLOSED"
    on_release:
      then:
        - logger.log: "Gate is OPEN"

  # Physical button to control the gate
  # Assumes button is connected to GPIO12 (D6 on NodeMCU)
  - platform: gpio
    id: gate_button
    name: "Garage Gate Button"
    pin:
      number: GPIO12  # D6
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_on: 50ms
      - delayed_off: 50ms
    on_press:
      then:
        - logger.log: "Button pressed - triggering gate relay"
        - switch.turn_on: gate_relay
        - delay: 500ms
        - switch.turn_off: gate_relay

# Relay to control the garage gate
# Assumes relay is connected to GPIO13 (D7 on NodeMCU)
switch:
  - platform: gpio
    id: gate_relay
    name: "Garage Gate Relay"
    pin:
      number: GPIO13  # D7
      inverted: false
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - logger.log: "Gate relay activated"
    on_turn_off:
      - logger.log: "Gate relay deactivated"

# Cover component for better Home Assistant integration
# This presents the garage gate as a cover entity
cover:
  - platform: template
    name: "Garage Gate"
    device_class: garage
    lambda: |-
      if (id(gate_contactron).state) {
        return COVER_OPEN;
      } else {
        return COVER_CLOSED;
      }
    open_action:
      # Only trigger if gate is currently closed
      - if:
          condition:
            binary_sensor.is_off: gate_contactron
          then:
            - logger.log: "Opening garage gate"
            - switch.turn_on: gate_relay
            - delay: 500ms
            - switch.turn_off: gate_relay
    close_action:
      # Only trigger if gate is currently open
      - if:
          condition:
            binary_sensor.is_on: gate_contactron
          then:
            - logger.log: "Closing garage gate"
            - switch.turn_on: gate_relay
            - delay: 500ms
            - switch.turn_off: gate_relay
    stop_action:
      # Trigger relay to stop the gate
      - logger.log: "Stopping garage gate"
      - switch.turn_on: gate_relay
      - delay: 500ms
      - switch.turn_off: gate_relay

# Sensor to show WiFi signal strength
sensor:
  - platform: wifi_signal
    name: "Garage Gate WiFi Signal"
    update_interval: 60s

# Text sensor to show IP address and ESPHome version
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "Garage Gate IP Address"
    ssid:
      name: "Garage Gate Connected SSID"
  - platform: version
    name: "Garage Gate ESPHome Version"
