esphome:
  name: garage-gate-simple
  platform: ESP8266
  board: esp01_1m  # For ESP-01 or other minimal boards

# WiFi configuration
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  # Enable fallback hotspot
  ap:
    ssid: "Garage Fallback"
    password: !secret fallback_password

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

# Enable OTA updates
ota:
  - platform: esphome
    password: !secret ota_password

# Binary sensor for the contactron (gate position sensor)
# GPIO0 for ESP-01
binary_sensor:
  - platform: gpio
    id: gate_sensor
    name: "Garage Gate Sensor"
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    device_class: garage_door

  # Physical button to control the gate
  # GPIO2 for ESP-01
  - platform: gpio
    id: gate_button
    name: "Gate Button"
    pin:
      number: GPIO2
      mode:
        input: true
        pullup: true
      inverted: true
    on_press:
      - switch.turn_on: gate_relay
      - delay: 500ms
      - switch.turn_off: gate_relay

# Relay to control the garage gate
# GPIO3 (RX) for ESP-01 - Note: This disables serial logging!
switch:
  - platform: gpio
    id: gate_relay
    name: "Gate Relay"
    pin: GPIO3
    restore_mode: ALWAYS_OFF

# Simple cover integration
cover:
  - platform: template
    name: "Garage Gate"
    device_class: garage
    lambda: |-
      if (id(gate_sensor).state) {
        return COVER_OPEN;
      } else {
        return COVER_CLOSED;
      }
    open_action:
      - switch.turn_on: gate_relay
      - delay: 500ms
      - switch.turn_off: gate_relay
    close_action:
      - switch.turn_on: gate_relay
      - delay: 500ms
      - switch.turn_off: gate_relay
    stop_action:
      - switch.turn_on: gate_relay
      - delay: 500ms
      - switch.turn_off: gate_relay
